services:

  auth:
    build:
      context: ./backend/authService
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  streaming:
    build:
      context: ./backend/streamingService
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - streaming
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Piyushsharma
      MONGO_INITDB_ROOT_PASSWORD: Piyush123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Piyushsharma
      ME_CONFIG_MONGODB_ADMINPASSWORD: Piyush123
      ME_CONFIG_MONGODB_URL: mongodb://Piyushsharma:Piyush123@mongo:27017/
      ME_CONFIG_BASICAUTH: false